export const PROFESSIONS = {
    ENTREPRENEUR: {
        id: 'ENTREPRENEUR',
        name: '企業家',
        icon: '💼',
        color: '#ffd700',
        description: '經驗豐富的商界領袖，擅長資源整合。',
        skills: '初始資金 +$5,000，買地與建築 8 折',
        bonusInitial: 5000,
        buyDiscount: 0.2,
    },
    LANDLORD: {
        id: 'LANDLORD',
        name: '包租公',
        icon: '🏠',
        color: '#ff66b2',
        description: '坐擁多處精華地段的資深大地主。',
        skills: '過路費收入 +30%',
        rentBonus: 0.3,
    },
    TRAVELER: {
        id: 'TRAVELER',
        name: '旅行者',
        icon: '✈️',
        color: '#00ffff',
        description: '嚮往自由的環球旅人，熟悉各地交通。',
        skills: '高鐵免費，起點獎金 $2,500',
        stationDiscount: 0,
        goBonus: 2500,
    },
    GAMBLER: {
        id: 'GAMBLER',
        name: '博弈家',
        icon: '🎰',
        color: '#ff4500',
        description: '在概率與命運中穿梭的冒險者。',
        skills: '雙子獎勵 $3,000，保釋金 $1,000',
        doubleBonus: 3000,
        bailCost: 1000,
    },
    POLICE: {
        id: 'POLICE',
        name: '警員',
        icon: '👮',
        color: '#1e90ff',
        description: '維護正義與城市秩序的英勇執法者。',
        skills: '免保釋金，路過或停留監獄領 $2,000',
        freeBail: true,
        jailVisitBonus: 2000,
    },
    BEGGAR: {
        id: 'BEGGAR',
        name: '乞丐',
        icon: '🍚',
        color: '#8b4513',
        description: '歷經滄桑的流浪者，看透世間人情。',
        skills: '初始資金 $1,500，買地與建築 7 折，若資產為最後一名，則每次擲骰獲得點數 x 85資金',
        bonusInitial: -13500,
        beggarMultiplier: 85,
        buyDiscount: 0.3
    },
    NORMAL: {
        id: 'NORMAL',
        name: '普通人',
        icon: '👨‍💼',
        color: '#cccccc',
        description: '過著平凡生活的普通市民。',
        skills: '無特殊能力'
    },
    TYCOON: {
        id: 'TYCOON',
        name: '富豪',
        icon: '💎',
        color: '#e0ffff',
        description: '掌握城市核心命脈，資財雄厚的大亨。',
        skills: '初始 $30,000，無起點獎金',
        bonusInitial: 15000,
        goBonus: 0
    },
    HOOLIGAN: {
        id: 'HOOLIGAN',
        name: '流氓',
        icon: '🔫',
        color: '#ff4444',
        description: '橫行霸道的街頭霸主，沒人敢收他的過路費。',
        skills: '起點獲 $1,000，路過地反收 40% 保護費 (上限 $5,000)，保釋 $2,500',
        goBonus: 1000,
        bailCost: 2500,
        isHooligan: true,
        protectionFeeRate: 0.4
    }
};
